// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _NotLoggedInLayout = "_NotLoggedInLayout";
                public readonly string _ProgressBar = "_ProgressBar";
                public readonly string _ProjectHeader = "_ProjectHeader";
                public readonly string Error = "Error";
                public readonly string FeatureSlider = "FeatureSlider";
                public readonly string Lockout = "Lockout";
                public readonly string PartialForAnonymous = "PartialForAnonymous";
                public readonly string PartialForLogged = "PartialForLogged";
            }
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _NotLoggedInLayout = "~/Views/Shared/_NotLoggedInLayout.cshtml";
            public readonly string _ProgressBar = "~/Views/Shared/_ProgressBar.cshtml";
            public readonly string _ProjectHeader = "~/Views/Shared/_ProjectHeader.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string FeatureSlider = "~/Views/Shared/FeatureSlider.cshtml";
            public readonly string Lockout = "~/Views/Shared/Lockout.cshtml";
            public readonly string PartialForAnonymous = "~/Views/Shared/PartialForAnonymous.cshtml";
            public readonly string PartialForLogged = "~/Views/Shared/PartialForLogged.cshtml";
            static readonly _MenuClass s_Menu = new _MenuClass();
            public _MenuClass Menu { get { return s_Menu; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _MenuClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string default_menu = "default_menu";
                    public readonly string developer_menu = "developer_menu";
                    public readonly string observer_menu = "observer_menu";
                    public readonly string projectManager_menu = "projectManager_menu";
                }
                public readonly string default_menu = "~/Views/Shared/Menu/default_menu.cshtml";
                public readonly string developer_menu = "~/Views/Shared/Menu/developer_menu.cshtml";
                public readonly string observer_menu = "~/Views/Shared/Menu/observer_menu.cshtml";
                public readonly string projectManager_menu = "~/Views/Shared/Menu/projectManager_menu.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
